### ISSUE TITLE
Where is Tutorial3_2Screen7?

### ISSUE THREAD

**Issue by alvindizon** [SmartToolFactory/Jetpack-Compose-Tutorials#1]
I just cloned the latest version of this repo and when I tried to build it, it seems that the composable `Tutorial3_2Screen7` is missing.

**Comment by SmartToolFactory** [comment]
Sorry, i'm current updating Constraints, Layout, Measurable tutorials. I probably missed it while renaming tutorials

**Comment by alvindizon** [comment]
Thank you, great repository BTW, this is a great learning resource!
