### ISSUE TITLE
Compose Previews are Missing

### ISSUE THREAD

**Issue by Naveed-Baloch** [SmartToolFactory/Jetpack-Compose-Tutorials#24]
## Description
Compose Previews are Missing

## Solution
Add Compose Previews.

<hr>

**Note:** I am willing to do the work and submit a PR.

**Comment by SmartToolFactory** [comment]
It would be nice if you add Reviews for missing ones, thanks in advance. I added for most of them but some still might be missing.

**Comment by Naveed-Baloch** [comment]
I am planning to submit separate PRs for each tutorial/module. Is that acceptable?
